name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      # Specify branch from where you are sharing build
      - default

jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          # Specify branch from where you are sharing build
          ref: 'default'
      - name: Setting up JDK 1.7
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Running build command
        # Run your own gradle command to generate build.
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab  

  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle
#      - name: Uploading to IAS
#         id: ias
#      	uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
#      	with:
#          # Your service account JSON GitHub secret
#      	  serviceAccountJsonPlainText: ${{ secrets.[your-github-service-acc-json-secret] }}
#          # Your package name
#          packageName: 'ContactQR'
#          aabFilePath: 'app-release.aab'
#      - name: Sharing on slack
#        uses: rtCamp/action-slack-notify@v2.1.0
#        env:
#          # Your slack webhook GitHub secret
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          # Slack channel where you want to notify
#          SLACK_CHANNEL: [your-channel]
#          SLACK_USERNAME: "JARVIS"
#          SLACK_TITLE: "Internal testing build"
#          SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}
#
